### ISSUE TITLE
favicon配置无效

### ISSUE THREAD

**Issue by saltfish233** [cnbloglabs/theme-geek#2]
如图，favicon赋值后站点图标没有改变。
![image](https://user-images.githubusercontent.com/50053654/194290179-4f044320-4a1b-45de-aebc-62ee9e752632.png)

![image](https://user-images.githubusercontent.com/50053654/194290361-9512907c-c6b0-41fa-b574-a2ea0fc471a6.png)

**Comment by S1mpleBug** [comment]
@saltfish233 这里有对该功能的解决方案，按照以下四步你可以不依赖于该主题，自己实现自定义标签图标：

### 第一步：挑挑拣拣
选一张icon图标（尺寸不要太大）不然加载会很慢，如果想通过自己的图片生成favicon，可以使用这个网站：[🔗[Favicon Generator. For real.](https://realfavicongenerator.net/#.XDBOgc_7RKM)]

### 第二步：传文档
在博客园的「设置」界面选择「文档」，将你喜欢的图片上传上来，获取该图片的链接地址

### 第三步：写代码
在设置中的「页脚Html代码」中插入以下script脚本，代码如下，记得将你自己的图片地址替换到`linkObject.href`中：

```html
<script type="text/javascript" language="javascript">
　　//Setting ico for cnblogs
　　var linkObject = document.createElement('link');
　　linkObject.rel = "shortcut icon";
　　linkObject.href = "https://files.cnblogs.com/files/yaoyaoliu/favicon.ico";
　　document.getElementsByTagName("head")[0].appendChild(linkObject);
</script>
```

### 第四步：刷新检验
保存——重新进入你的博客首页——发现大功告成，新的icon图标已经生效了。

**Comment by saltfish233** [comment]
> 

解决了，非常感谢🙇‍
